#server:
#  port: 10010
#spring:
#  application:
#    name: gateway # 应用名称，会在Eureka中显示
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#    gateway:
#      routes:
#        - id: order
#          uri: lb://order-server/
#          predicates:
#            - Path=/order/**
#        - id: user
#          uri: lb://user-server/
#          predicates:
#            - Path=/user/**
#      discovery:
#        locator:
#          enabled: true
#
##eureka:
##  client:
##    service-url: # EurekaServer的地址，现在是自己的地址，如果是集群，需要加上其它Server的地址。
##      defaultZone: http://127.0.0.1:10086/eureka